In [5]:
import numpy as np
from numpy.linalg import lstsq

In [6]:
# Given data for Problem 1
weights = np.array([4800, 3700, 3400, 2800, 1900])  # in lbs
percent_occurrence = np.array([3.1, 4.8, 5.2, 6.4, 8.6])  # in percent

# Setting up the matrices for the least squares calculation
# X matrix with a column of ones for the intercept
X = np.vstack([weights, np.ones(len(weights))]).T
y = percent_occurrence

print(X)
print(y)


[[4.8e+03 1.0e+00]
 [3.7e+03 1.0e+00]
 [3.4e+03 1.0e+00]
 [2.8e+03 1.0e+00]
 [1.9e+03 1.0e+00]]
[3.1 4.8 5.2 6.4 8.6]


In [7]:
# Least squares approximation
m, b = lstsq(X, y, rcond=None)[0]

# Use the line to predict the chance for a 3000 lb car
predicted_weight = 3000
predicted_chance = m * predicted_weight + b

In [8]:
# Output the slope, intercept, and predicted chance
(m, b, predicted_chance)

(-0.0018824546240276585, 11.869749351771821, 6.222385479688845)

# Alternative way to compute this

In [9]:
# Another way of looking at it mathematically

XT_X = X.T.dot(X)
inv_XT_X = np.linalg.inv(XT_X)

XT_y = X.T.dot(y)

least_squares_solution = inv_XT_X.dot(XT_y)

least_squares_solution

array([-1.88245462e-03,  1.18697494e+01])

In [11]:
least_squares_solution[0] * predicted_weight + least_squares_solution[1]

6.222385479688853